// <auto-generated />
using System;
using Database.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Database.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20221022161722_product")]
    partial class product
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Database.Entities.Bills", b =>
                {
                    b.Property<string>("bill_Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("bill_Cancel")
                        .HasColumnType("bit");

                    b.Property<DateTime>("bill_StartDateTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("bill_StatusPayment")
                        .HasColumnType("bit");

                    b.Property<bool>("bill_StatusReviceOrder")
                        .HasColumnType("bit");

                    b.Property<double>("bill_Total")
                        .HasColumnType("float");

                    b.Property<string>("bill_UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("bill_Id");

                    b.HasIndex("bill_UserId");

                    b.ToTable("Bills", (string)null);

                    b.HasData(
                        new
                        {
                            bill_Id = "2f412223-c9f4-48eb-9924-8b216f31ee85",
                            bill_Cancel = false,
                            bill_StartDateTime = new DateTime(2022, 10, 22, 23, 17, 22, 26, DateTimeKind.Local).AddTicks(9361),
                            bill_StatusPayment = true,
                            bill_StatusReviceOrder = false,
                            bill_Total = 1.0,
                            bill_UserId = "5db2ec3d-8bcf-4bf9-81de-4730297b2f20"
                        });
                });

            modelBuilder.Entity("Database.Entities.IntroducePage", b =>
                {
                    b.Property<string>("introduce_Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("introduce_Address1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("introduce_Address2")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("introduce_Address3")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("introduce_Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("introduce_Map1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("introduce_Map2")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("introduce_Map3")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("introduce_Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("introduce_UserCreate")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("introduce_Zalo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("introduce_Id");

                    b.HasIndex("introduce_UserCreate");

                    b.ToTable("IntroducePage", (string)null);
                });

            modelBuilder.Entity("Database.Entities.PetCategories", b =>
                {
                    b.Property<string>("pc_Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("pc_Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("pc_IsDelete")
                        .HasColumnType("bit");

                    b.Property<string>("pc_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("pc_Id");

                    b.ToTable("PetCategories", (string)null);

                    b.HasData(
                        new
                        {
                            pc_Id = "5fac894a-a012-4abc-941b-c097ee7a2fe1",
                            pc_Description = "Ikita Inu",
                            pc_IsDelete = false,
                            pc_Name = "Ikita Inu"
                        },
                        new
                        {
                            pc_Id = "101f2f0b-7634-43ce-b9cf-01b06bae6b86",
                            pc_Description = "Alaska",
                            pc_IsDelete = false,
                            pc_Name = "Alaska"
                        },
                        new
                        {
                            pc_Id = "18905cfe-2b9e-43ce-8f6b-b5714e7b5803",
                            pc_Description = "Vitespitz",
                            pc_IsDelete = false,
                            pc_Name = "Vitespitz"
                        },
                        new
                        {
                            pc_Id = "c0deabcd-59e4-4655-acc8-8a4fca01b723",
                            pc_Description = "Pekingese",
                            pc_IsDelete = false,
                            pc_Name = "Pekingese"
                        },
                        new
                        {
                            pc_Id = "bea8fcc8-3ed8-4f23-8f9d-e8b9ad5be0e5",
                            pc_Description = "Becgie Germany",
                            pc_IsDelete = false,
                            pc_Name = "Becgie Germany"
                        },
                        new
                        {
                            pc_Id = "8daf3fdf-f65a-4221-ace2-d117f2db8508",
                            pc_Description = "Border collie",
                            pc_IsDelete = false,
                            pc_Name = "Border collie"
                        },
                        new
                        {
                            pc_Id = "8fb6624f-b9e6-4cd1-8e19-bbacbc8ffc9a",
                            pc_Description = "Bulldog",
                            pc_IsDelete = false,
                            pc_Name = "Bulldog"
                        },
                        new
                        {
                            pc_Id = "ddfc77ba-a221-49ed-8e7c-d4efcd7f0a61",
                            pc_Description = "Bully American",
                            pc_IsDelete = false,
                            pc_Name = "Bully American"
                        },
                        new
                        {
                            pc_Id = "d14c67d5-4a42-4221-ab15-268a0de34613",
                            pc_Description = "Chihuahua",
                            pc_IsDelete = false,
                            pc_Name = "Chihuahua"
                        },
                        new
                        {
                            pc_Id = "6432edba-2d75-4485-884f-c19e221cbbac",
                            pc_Description = "Dalmatian",
                            pc_IsDelete = false,
                            pc_Name = "Dalmatian"
                        },
                        new
                        {
                            pc_Id = "efe4cbd8-52e4-4099-a410-d5d696517fdf",
                            pc_Description = "Japan Dog",
                            pc_IsDelete = false,
                            pc_Name = "Japan Dog"
                        },
                        new
                        {
                            pc_Id = "ddaee95e-695b-4a68-bd4a-e9d020305e71",
                            pc_Description = "Chow Chow",
                            pc_IsDelete = false,
                            pc_Name = "Chow Chow"
                        },
                        new
                        {
                            pc_Id = "77e950ee-45de-45b4-b415-6a83b1c28500",
                            pc_Description = "Cocker Spaniel",
                            pc_IsDelete = false,
                            pc_Name = "Cocker Spaniel"
                        },
                        new
                        {
                            pc_Id = "eccf607d-6302-41ee-b4e6-a36ff75f0a82",
                            pc_Description = "Corgi",
                            pc_IsDelete = false,
                            pc_Name = "Corgi"
                        },
                        new
                        {
                            pc_Id = "9e97181b-b251-409f-bbaa-6fcb797ef03c",
                            pc_Description = "Dobermann",
                            pc_IsDelete = false,
                            pc_Name = "Dobermann"
                        },
                        new
                        {
                            pc_Id = "25dafb34-a58e-4757-a3e9-35b9ab226a88",
                            pc_Description = "Golden Retriever",
                            pc_IsDelete = false,
                            pc_Name = "Golden Retriever"
                        },
                        new
                        {
                            pc_Id = "d7f0e948-5917-4c6b-ba0b-07d579270c7f",
                            pc_Description = "Great Dane",
                            pc_IsDelete = false,
                            pc_Name = "Great Dane"
                        },
                        new
                        {
                            pc_Id = "38822d47-f05e-484f-9af4-5d1334ddb01e",
                            pc_Description = "H'Mong Coc",
                            pc_IsDelete = false,
                            pc_Name = "H'Mong Coc"
                        },
                        new
                        {
                            pc_Id = "183b7352-ad15-4fa7-967c-c2639e1adcb3",
                            pc_Description = "Husky",
                            pc_IsDelete = false,
                            pc_Name = "Husky"
                        },
                        new
                        {
                            pc_Id = "8637cef8-dd50-4fcc-ab09-902d8db07f44",
                            pc_Description = "Labrador",
                            pc_IsDelete = false,
                            pc_Name = "Labrador"
                        },
                        new
                        {
                            pc_Id = "7a8a923e-26d5-40ee-aaab-1f1755f5ed0a",
                            pc_Description = "Sausage",
                            pc_IsDelete = false,
                            pc_Name = "Sausage"
                        },
                        new
                        {
                            pc_Id = "d283ff48-dfa0-41ff-8cc2-2997596fbc7e",
                            pc_Description = "Malinois",
                            pc_IsDelete = false,
                            pc_Name = "Malinois"
                        },
                        new
                        {
                            pc_Id = "b506f21e-e608-417b-90b5-012c3ca93db1",
                            pc_Description = "Tibetan Clams",
                            pc_IsDelete = false,
                            pc_Name = "Tibetan Clams"
                        },
                        new
                        {
                            pc_Id = "0edd9af8-634d-4dfe-8f68-3f6a4f649f8a",
                            pc_Description = "Pho Deer",
                            pc_IsDelete = false,
                            pc_Name = "Pho Deer"
                        },
                        new
                        {
                            pc_Id = "7a859a9b-8ef6-4519-a36e-4d5c008c3380",
                            pc_Description = "Phoc Soc",
                            pc_IsDelete = false,
                            pc_Name = "Phoc Soc"
                        },
                        new
                        {
                            pc_Id = "4750bd6e-3013-439d-9147-458fb635a26c",
                            pc_Description = "Phu Quoc",
                            pc_IsDelete = false,
                            pc_Name = "Phu Quoc"
                        },
                        new
                        {
                            pc_Id = "cc70426a-f0f6-4e37-9672-9a1f5e999fde",
                            pc_Description = "Pitbull",
                            pc_IsDelete = false,
                            pc_Name = "Pitbull"
                        },
                        new
                        {
                            pc_Id = "dadba9e0-ee05-457a-9462-12a038b2dc9f",
                            pc_Description = "Poodle",
                            pc_IsDelete = false,
                            pc_Name = "Poodle"
                        },
                        new
                        {
                            pc_Id = "3596fe4a-998f-417d-878d-6b82073fe30c",
                            pc_Description = "Pug",
                            pc_IsDelete = false,
                            pc_Name = "Pug"
                        },
                        new
                        {
                            pc_Id = "bb6b5a90-b5e1-452d-b39a-c90f46184515",
                            pc_Description = "Rottweiler",
                            pc_IsDelete = false,
                            pc_Name = "Rottweiler"
                        },
                        new
                        {
                            pc_Id = "4b7c3ed1-1560-41a3-99b6-43ce7cd5a136",
                            pc_Description = "Samoyed",
                            pc_IsDelete = false,
                            pc_Name = "Samoyed"
                        },
                        new
                        {
                            pc_Id = "2c76ff0f-f000-4ccd-903a-dd81b8386391",
                            pc_Description = "Shiba Inu",
                            pc_IsDelete = false,
                            pc_Name = "Shiba Inu"
                        });
                });

            modelBuilder.Entity("Database.Entities.Pets", b =>
                {
                    b.Property<string>("pet_Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("pet_CategoryId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("pet_Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("pet_Image1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("pet_Image2")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("pet_Image3")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("pet_Image4")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("pet_Image5")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("pet_IsDelete")
                        .HasColumnType("bit");

                    b.Property<double>("pet_Lifespan")
                        .HasColumnType("float");

                    b.Property<string>("pet_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("pet_Origin")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("pet_OrtherName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("pet_Price")
                        .HasColumnType("float");

                    b.Property<double>("pet_Weight")
                        .HasColumnType("float");

                    b.HasKey("pet_Id");

                    b.HasIndex("pet_CategoryId");

                    b.ToTable("Pets", (string)null);
                });

            modelBuilder.Entity("Database.Entities.PettInBill", b =>
                {
                    b.Property<string>("pib_PetId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("pib_BillId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("pib_IsDelete")
                        .HasColumnType("bit");

                    b.Property<double>("pib_Price")
                        .HasColumnType("float");

                    b.Property<double>("pib_Quantity")
                        .HasColumnType("float");

                    b.HasKey("pib_PetId", "pib_BillId");

                    b.HasIndex("pib_BillId");

                    b.ToTable("PettInBill", (string)null);

                    b.HasData(
                        new
                        {
                            pib_PetId = "0d601915-9c63-4ae7-b227-544669f84e54",
                            pib_BillId = "2f412223-c9f4-48eb-9924-8b216f31ee85",
                            pib_IsDelete = false,
                            pib_Price = 12.0,
                            pib_Quantity = 1.0
                        });
                });

            modelBuilder.Entity("Database.Entities.ProductCategories", b =>
                {
                    b.Property<string>("proc_Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("proc_Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("proc_IsDelete")
                        .HasColumnType("bit");

                    b.Property<string>("proc_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("proc_Id");

                    b.ToTable("ProductCategories", (string)null);

                    b.HasData(
                        new
                        {
                            proc_Id = "977d57c9-4b90-42bd-9c26-1ccf6aaf4005",
                            proc_Description = "Pet Supplies",
                            proc_IsDelete = false,
                            proc_Name = "Pet Supplies"
                        },
                        new
                        {
                            proc_Id = "d58b3306-4e7a-494a-a8c8-9fc37834a393",
                            proc_Description = "Pet Food",
                            proc_IsDelete = false,
                            proc_Name = "Pet Food"
                        },
                        new
                        {
                            proc_Id = "25796aad-8886-4baa-89ea-ab60e9622e32",
                            proc_Description = "Pet Cage",
                            proc_IsDelete = false,
                            proc_Name = "Pet Cage"
                        },
                        new
                        {
                            proc_Id = "31aee0ec-e0c5-4bed-8e70-b71befb70b25",
                            proc_Description = "Pet Toys",
                            proc_IsDelete = false,
                            proc_Name = "Pet Toys"
                        },
                        new
                        {
                            proc_Id = "73a8b868-f082-4802-a298-559c72e707e9",
                            proc_Description = "Beauty Accessories",
                            proc_IsDelete = false,
                            proc_Name = "Beauty Accessories"
                        },
                        new
                        {
                            proc_Id = "7530f132-1e23-4e07-b3b9-0f1a8f559c8b",
                            proc_Description = "Pet Clothes",
                            proc_IsDelete = false,
                            proc_Name = "Pet Clothes"
                        },
                        new
                        {
                            proc_Id = "37ff9faf-1464-4589-ac20-139f829060ef",
                            proc_Description = "Nutritional Food",
                            proc_IsDelete = false,
                            proc_Name = "Nutritional Food"
                        },
                        new
                        {
                            proc_Id = "87c52723-537d-4378-80c3-556e24822d8f",
                            proc_Description = "Medicines & Functional Products",
                            proc_IsDelete = false,
                            proc_Name = "Medicines & Functional Products"
                        });
                });

            modelBuilder.Entity("Database.Entities.ProductInBill", b =>
                {
                    b.Property<string>("proib_ProductId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("proib_BillId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("proib_IsDelete")
                        .HasColumnType("bit");

                    b.Property<double>("proib_Price")
                        .HasColumnType("float");

                    b.Property<double>("proib_Quantity")
                        .HasColumnType("float");

                    b.HasKey("proib_ProductId", "proib_BillId");

                    b.HasIndex("proib_BillId");

                    b.ToTable("ProductInBill", (string)null);

                    b.HasData(
                        new
                        {
                            proib_ProductId = "37fb2a40-9bcd-4c36-991d-ac8c7d0ce75a",
                            proib_BillId = "2f412223-c9f4-48eb-9924-8b216f31ee85",
                            proib_IsDelete = false,
                            proib_Price = 12.0,
                            proib_Quantity = 1.0
                        });
                });

            modelBuilder.Entity("Database.Entities.Products", b =>
                {
                    b.Property<string>("product_Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("product_CategoryId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("product_Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("product_Image1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("product_Image2")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("product_Image3")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("product_Image4")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("product_Image5")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("product_IsDelete")
                        .HasColumnType("bit");

                    b.Property<string>("product_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("product_Price")
                        .HasColumnType("float");

                    b.Property<double>("product_Rate")
                        .HasColumnType("float");

                    b.Property<double>("product_ReProducePrice")
                        .HasColumnType("float");

                    b.HasKey("product_Id");

                    b.HasIndex("product_CategoryId");

                    b.ToTable("Products", (string)null);

                    b.HasData(
                        new
                        {
                            product_Id = "37fb2a40-9bcd-4c36-991d-ac8c7d0ce75a",
                            product_CategoryId = "977d57c9-4b90-42bd-9c26-1ccf6aaf4005",
                            product_Description = "Transparent Backpack For Dogs and Cats",
                            product_Image1 = "image/phukien/phukien-balotrongsuot.png",
                            product_Image2 = "image/phukien/phukien-balotrongsuot.png",
                            product_Image3 = "image/phukien/phukien-balotrongsuot.png",
                            product_Image4 = "image/phukien/phukien-balotrongsuot.png",
                            product_Image5 = "image/phukien/phukien-balotrongsuot.png",
                            product_IsDelete = false,
                            product_Name = "Transparent Backpack For Dogs and Cats",
                            product_Price = 100000.0,
                            product_Rate = 5.0,
                            product_ReProducePrice = 0.0
                        },
                        new
                        {
                            product_Id = "afcc65a4-bf1a-421e-8d10-5984b5bc7a6a",
                            product_CategoryId = "977d57c9-4b90-42bd-9c26-1ccf6aaf4005",
                            product_Description = "Training Whistle",
                            product_Image1 = "image/phukien/phukien-coihuanluyen.png",
                            product_Image2 = "image/phukien/phukien-coihuanluyen.png",
                            product_Image3 = "image/phukien/phukien-coihuanluyen.png",
                            product_Image4 = "image/phukien/phukien-coihuanluyen.png",
                            product_Image5 = "image/phukien/phukien-coihuanluyen.png",
                            product_IsDelete = false,
                            product_Name = "Training Whistle",
                            product_Price = 100000.0,
                            product_Rate = 5.0,
                            product_ReProducePrice = 0.0
                        },
                        new
                        {
                            product_Id = "134426be-d66d-45f8-8b7d-0a419d5a3f2b",
                            product_CategoryId = "977d57c9-4b90-42bd-9c26-1ccf6aaf4005",
                            product_Description = "Lamb Sticks",
                            product_Image1 = "image/phukien/phukien-thitcuuque.png",
                            product_Image2 = "image/phukien/phukien-thitcuuque.png",
                            product_Image3 = "image/phukien/phukien-thitcuuque.png",
                            product_Image4 = "image/phukien/phukien-thitcuuque.png",
                            product_Image5 = "image/phukien/phukien-thitcuuque.png",
                            product_IsDelete = false,
                            product_Name = "Lamb Sticks",
                            product_Price = 100000.0,
                            product_Rate = 5.0,
                            product_ReProducePrice = 0.0
                        },
                        new
                        {
                            product_Id = "3e8390be-0c86-4442-bba2-bcca42285af8",
                            product_CategoryId = "977d57c9-4b90-42bd-9c26-1ccf6aaf4005",
                            product_Description = "SmartHeart For Small Dogs",
                            product_Image1 = "image/phukien/phukien-SmartHeart.png",
                            product_Image2 = "image/phukien/phukien-SmartHeart.png",
                            product_Image3 = "image/phukien/phukien-SmartHeart.png",
                            product_Image4 = "image/phukien/phukien-SmartHeart.png",
                            product_Image5 = "image/phukien/phukien-SmartHeart.png",
                            product_IsDelete = false,
                            product_Name = "SmartHeart For Small Dogs",
                            product_Price = 100000.0,
                            product_Rate = 5.0,
                            product_ReProducePrice = 0.0
                        },
                        new
                        {
                            product_Id = "a46ebd81-bdbf-4ee6-a43b-1026131d25fb",
                            product_CategoryId = "977d57c9-4b90-42bd-9c26-1ccf6aaf4005",
                            product_Description = "Bonus Cake Tablet",
                            product_Image1 = "image/phukien/phukien-banhthuong.png",
                            product_Image2 = "image/phukien/phukien-banhthuong.png",
                            product_Image3 = "image/phukien/phukien-banhthuong.png",
                            product_Image4 = "image/phukien/phukien-banhthuong.png",
                            product_Image5 = "image/phukien/phukien-banhthuong.png",
                            product_IsDelete = false,
                            product_Name = "Bonus Cake Tablet",
                            product_Price = 100000.0,
                            product_Rate = 5.0,
                            product_ReProducePrice = 0.0
                        },
                        new
                        {
                            product_Id = "293cd544-4b5b-493d-8af2-9a5871dca7e0",
                            product_CategoryId = "977d57c9-4b90-42bd-9c26-1ccf6aaf4005",
                            product_Description = "Royal Canin For Adult Dogs",
                            product_Image1 = "image/phukien/phukien-royal_truongthanh.png",
                            product_Image2 = "image/phukien/phukien-royal_truongthanh.png",
                            product_Image3 = "image/phukien/phukien-royal_truongthanh.png",
                            product_Image4 = "image/phukien/phukien-royal_truongthanh.png",
                            product_Image5 = "image/phukien/phukien-royal_truongthanh.png",
                            product_IsDelete = false,
                            product_Name = "Royal Canin For Adult Dogs",
                            product_Price = 100000.0,
                            product_Rate = 5.0,
                            product_ReProducePrice = 0.0
                        },
                        new
                        {
                            product_Id = "4b231fba-8a16-488a-80bf-f52e275924f5",
                            product_CategoryId = "977d57c9-4b90-42bd-9c26-1ccf6aaf4005",
                            product_Description = "Pair of Bows",
                            product_Image1 = "image/phukien/phukien-capno.png",
                            product_Image2 = "image/phukien/phukien-capno.png",
                            product_Image3 = "image/phukien/phukien-capno.png",
                            product_Image4 = "image/phukien/phukien-capno.png",
                            product_Image5 = "image/phukien/phukien-capno.png",
                            product_IsDelete = false,
                            product_Name = "Pair of Bows",
                            product_Price = 100000.0,
                            product_Rate = 5.0,
                            product_ReProducePrice = 0.0
                        },
                        new
                        {
                            product_Id = "b93d7d75-4d7c-4056-b780-f4c57a5ad014",
                            product_CategoryId = "977d57c9-4b90-42bd-9c26-1ccf6aaf4005",
                            product_Description = "Princess Lace Scarf",
                            product_Image1 = "image/phukien/phukien-khanren.png",
                            product_Image2 = "image/phukien/phukien-khanren.png",
                            product_Image3 = "image/phukien/phukien-khanren.png",
                            product_Image4 = "image/phukien/phukien-khanren.png",
                            product_Image5 = "image/phukien/phukien-khanren.png",
                            product_IsDelete = false,
                            product_Name = "Princess Lace Scarf",
                            product_Price = 100000.0,
                            product_Rate = 5.0,
                            product_ReProducePrice = 0.0
                        },
                        new
                        {
                            product_Id = "4c9c99eb-50f6-4bfb-81e6-7502d6d8a20b",
                            product_CategoryId = "977d57c9-4b90-42bd-9c26-1ccf6aaf4005",
                            product_Description = "Drugs of Calcium",
                            product_Image1 = "image/phukien/phukien-thuoccanxi.png",
                            product_Image2 = "image/phukien/phukien-thuoccanxi.png",
                            product_Image3 = "image/phukien/phukien-thuoccanxi.png",
                            product_Image4 = "image/phukien/phukien-thuoccanxi.png",
                            product_Image5 = "image/phukien/phukien-thuoccanxi.png",
                            product_IsDelete = false,
                            product_Name = "Drugs of Calcium",
                            product_Price = 100000.0,
                            product_Rate = 5.0,
                            product_ReProducePrice = 0.0
                        },
                        new
                        {
                            product_Id = "82d4e33c-453f-4041-af0d-350fe2929aba",
                            product_CategoryId = "977d57c9-4b90-42bd-9c26-1ccf6aaf4005",
                            product_Description = "Bow Bow Bra",
                            product_Image1 = "image/phukien/phukien-aongucnochuong.png",
                            product_Image2 = "image/phukien/phukien-aongucnochuong.png",
                            product_Image3 = "image/phukien/phukien-aongucnochuong.png",
                            product_Image4 = "image/phukien/phukien-aongucnochuong.png",
                            product_Image5 = "image/phukien/phukien-aongucnochuong.png",
                            product_IsDelete = false,
                            product_Name = "Bow Bow Bra",
                            product_Price = 100000.0,
                            product_Rate = 5.0,
                            product_ReProducePrice = 0.0
                        },
                        new
                        {
                            product_Id = "1e36caa4-8c07-4be5-9691-c700fa2f0195",
                            product_CategoryId = "977d57c9-4b90-42bd-9c26-1ccf6aaf4005",
                            product_Description = "Balloon Toys",
                            product_Image1 = "image/phukien/phukien-bongbongdochoi.png",
                            product_Image2 = "image/phukien/phukien-bongbongdochoi.png",
                            product_Image3 = "image/phukien/phukien-bongbongdochoi.png",
                            product_Image4 = "image/phukien/phukien-bongbongdochoi.png",
                            product_Image5 = "image/phukien/phukien-bongbongdochoi.png",
                            product_IsDelete = false,
                            product_Name = "Balloon Toys",
                            product_Price = 100000.0,
                            product_Rate = 5.0,
                            product_ReProducePrice = 0.0
                        },
                        new
                        {
                            product_Id = "74a279ee-6f70-41fe-801b-940ba3700fd3",
                            product_CategoryId = "977d57c9-4b90-42bd-9c26-1ccf6aaf4005",
                            product_Description = "Dog Fence",
                            product_Image1 = "image/phukien/phukien-raoquaycho.png",
                            product_Image2 = "image/phukien/phukien-raoquaycho.png",
                            product_Image3 = "image/phukien/phukien-raoquaycho.png",
                            product_Image4 = "image/phukien/phukien-raoquaycho.png",
                            product_Image5 = "image/phukien/phukien-raoquaycho.png",
                            product_IsDelete = false,
                            product_Name = "Dog Fence",
                            product_Price = 100000.0,
                            product_Rate = 5.0,
                            product_ReProducePrice = 0.0
                        },
                        new
                        {
                            product_Id = "83c5f46d-18d1-48c0-9257-9eb81b2f7ce1",
                            product_CategoryId = "977d57c9-4b90-42bd-9c26-1ccf6aaf4005",
                            product_Description = "BLOOM SEXY Fragrance Bath Oil",
                            product_Image1 = "image/phukien/phukien-dautamnuochoabloomsexy.png",
                            product_Image2 = "image/phukien/phukien-dautamnuochoabloomsexy.png",
                            product_Image3 = "image/phukien/phukien-dautamnuochoabloomsexy.png",
                            product_Image4 = "image/phukien/phukien-dautamnuochoabloomsexy.png",
                            product_Image5 = "image/phukien/phukien-dautamnuochoabloomsexy.png",
                            product_IsDelete = false,
                            product_Name = "BLOOM SEXY Fragrance Bath Oil",
                            product_Price = 100000.0,
                            product_Rate = 5.0,
                            product_ReProducePrice = 0.0
                        },
                        new
                        {
                            product_Id = "1130512f-9f4d-48b6-87e3-ddb4d58d7ce2",
                            product_CategoryId = "977d57c9-4b90-42bd-9c26-1ccf6aaf4005",
                            product_Description = "Toys",
                            product_Image1 = "image/phukien/phukien-dochoi.png",
                            product_Image2 = "image/phukien/phukien-dochoi.png",
                            product_Image3 = "image/phukien/phukien-dochoi.png",
                            product_Image4 = "image/phukien/phukien-dochoi.png",
                            product_Image5 = "image/phukien/phukien-dochoi.png",
                            product_IsDelete = false,
                            product_Name = "Toys",
                            product_Price = 100000.0,
                            product_Rate = 5.0,
                            product_ReProducePrice = 0.0
                        },
                        new
                        {
                            product_Id = "d24f98f6-428c-4b63-b954-5d018a4e3573",
                            product_CategoryId = "977d57c9-4b90-42bd-9c26-1ccf6aaf4005",
                            product_Description = "BLOOM SEXY Fragrance Bath Oil",
                            product_Image1 = "image/phukien/phukien-dautamFay.png",
                            product_Image2 = "image/phukien/phukien-dautamFay.png",
                            product_Image3 = "image/phukien/phukien-dautamFay.png",
                            product_Image4 = "image/phukien/phukien-dautamFay.png",
                            product_Image5 = "image/phukien/phukien-dautamFay.png",
                            product_IsDelete = false,
                            product_Name = "BLOOM SEXY Fragrance Bath Oil",
                            product_Price = 100000.0,
                            product_Rate = 5.0,
                            product_ReProducePrice = 0.0
                        },
                        new
                        {
                            product_Id = "f539e402-932b-41d0-9868-c583e16f4e71",
                            product_CategoryId = "977d57c9-4b90-42bd-9c26-1ccf6aaf4005",
                            product_Description = "Anti-Tear Syrup",
                            product_Image1 = "image/phukien/phukien-sirochongchaynuocmat.png",
                            product_Image2 = "image/phukien/phukien-sirochongchaynuocmat.png",
                            product_Image3 = "image/phukien/phukien-sirochongchaynuocmat.png",
                            product_Image4 = "image/phukien/phukien-sirochongchaynuocmat.png",
                            product_Image5 = "image/phukien/phukien-sirochongchaynuocmat.png",
                            product_IsDelete = false,
                            product_Name = "Anti-Tear Syrup",
                            product_Price = 100000.0,
                            product_Rate = 5.0,
                            product_ReProducePrice = 0.0
                        },
                        new
                        {
                            product_Id = "e87f1c9b-3bc8-4f2f-be30-dfb3b8fced96",
                            product_CategoryId = "977d57c9-4b90-42bd-9c26-1ccf6aaf4005",
                            product_Description = "Lice Treatment Ring",
                            product_Image1 = "image/phukien/phukien-vongtriveran.png",
                            product_Image2 = "image/phukien/phukien-vongtriveran.png",
                            product_Image3 = "image/phukien/phukien-vongtriveran.png",
                            product_Image4 = "image/phukien/phukien-vongtriveran.png",
                            product_Image5 = "image/phukien/phukien-vongtriveran.png",
                            product_IsDelete = false,
                            product_Name = "Lice Treatment Ring",
                            product_Price = 100000.0,
                            product_Rate = 5.0,
                            product_ReProducePrice = 0.0
                        },
                        new
                        {
                            product_Id = "fbb79555-a0c5-4feb-aefd-e4bd91307288",
                            product_CategoryId = "977d57c9-4b90-42bd-9c26-1ccf6aaf4005",
                            product_Description = "HANTOC Lice Spray",
                            product_Image1 = "image/phukien/phukien-xitveranHANTOC.png",
                            product_Image2 = "image/phukien/phukien-xitveranHANTOC.png",
                            product_Image3 = "image/phukien/phukien-xitveranHANTOC.png",
                            product_Image4 = "image/phukien/phukien-xitveranHANTOC.png",
                            product_Image5 = "image/phukien/phukien-xitveranHANTOC.png",
                            product_IsDelete = false,
                            product_Name = "HANTOC Lice Spray",
                            product_Price = 100000.0,
                            product_Rate = 5.0,
                            product_ReProducePrice = 0.0
                        },
                        new
                        {
                            product_Id = "427176bd-a0f8-42b3-9bc2-278e2aee0d7f",
                            product_CategoryId = "977d57c9-4b90-42bd-9c26-1ccf6aaf4005",
                            product_Description = "Nutri-Nutrition Gel",
                            product_Image1 = "image/phukien/phukien-gelddNutri.png",
                            product_Image2 = "image/phukien/phukien-gelddNutri.png",
                            product_Image3 = "image/phukien/phukien-gelddNutri.png",
                            product_Image4 = "image/phukien/phukien-gelddNutri.png",
                            product_Image5 = "image/phukien/phukien-gelddNutri.png",
                            product_IsDelete = false,
                            product_Name = "Nutri-Nutrition Gel",
                            product_Price = 100000.0,
                            product_Rate = 5.0,
                            product_ReProducePrice = 0.0
                        },
                        new
                        {
                            product_Id = "098c911d-1a68-4bba-9c59-896452427333",
                            product_CategoryId = "977d57c9-4b90-42bd-9c26-1ccf6aaf4005",
                            product_Description = "Bio Milk Powder For Dogs and Cats",
                            product_Image1 = "image/phukien/phukien-suabotchomeo.png",
                            product_Image2 = "image/phukien/phukien-suabotchomeo.png",
                            product_Image3 = "image/phukien/phukien-suabotchomeo.png",
                            product_Image4 = "image/phukien/phukien-suabotchomeo.png",
                            product_Image5 = "image/phukien/phukien-suabotchomeo.png",
                            product_IsDelete = false,
                            product_Name = "Bio Milk Powder For Dogs and Cats",
                            product_Price = 100000.0,
                            product_Rate = 5.0,
                            product_ReProducePrice = 0.0
                        },
                        new
                        {
                            product_Id = "b6b5bb11-f7c9-4403-806c-95fc26d50120",
                            product_CategoryId = "977d57c9-4b90-42bd-9c26-1ccf6aaf4005",
                            product_Description = "Sleeky Multivitamin",
                            product_Image1 = "image/phukien/phukien-vitamintonghop.png",
                            product_Image2 = "image/phukien/phukien-vitamintonghop.png",
                            product_Image3 = "image/phukien/phukien-vitamintonghop.png",
                            product_Image4 = "image/phukien/phukien-vitamintonghop.png",
                            product_Image5 = "image/phukien/phukien-vitamintonghop.png",
                            product_IsDelete = false,
                            product_Name = "Sleeky Multivitamin",
                            product_Price = 100000.0,
                            product_Rate = 5.0,
                            product_ReProducePrice = 0.0
                        },
                        new
                        {
                            product_Id = "f45796b9-c616-4a89-bb17-250b891d6cf2",
                            product_CategoryId = "977d57c9-4b90-42bd-9c26-1ccf6aaf4005",
                            product_Description = "Canxi Nano",
                            product_Image1 = "image/phukien/phukien-canxinano.png",
                            product_Image2 = "image/phukien/phukien-canxinano.png",
                            product_Image3 = "image/phukien/phukien-canxinano.png",
                            product_Image4 = "image/phukien/phukien-canxinano.png",
                            product_Image5 = "image/phukien/phukien-canxinano.png",
                            product_IsDelete = false,
                            product_Name = "Canxi Nano",
                            product_Price = 100000.0,
                            product_Rate = 5.0,
                            product_ReProducePrice = 0.0
                        },
                        new
                        {
                            product_Id = "7cc95b97-cf65-4216-98ed-b104e951b7b4",
                            product_CategoryId = "977d57c9-4b90-42bd-9c26-1ccf6aaf4005",
                            product_Description = "Shipping Bag",
                            product_Image1 = "image/phukien/phukien-tuivanchuyen.png",
                            product_Image2 = "image/phukien/phukien-tuivanchuyen.png",
                            product_Image3 = "image/phukien/phukien-tuivanchuyen.png",
                            product_Image4 = "image/phukien/phukien-tuivanchuyen.png",
                            product_Image5 = "image/phukien/phukien-tuivanchuyen.png",
                            product_IsDelete = false,
                            product_Name = "Shipping Bag",
                            product_Price = 100000.0,
                            product_Rate = 5.0,
                            product_ReProducePrice = 0.0
                        },
                        new
                        {
                            product_Id = "211cd7e7-da5c-443b-8dcc-f8486cda1b00",
                            product_CategoryId = "977d57c9-4b90-42bd-9c26-1ccf6aaf4005",
                            product_Description = "Food Toys",
                            product_Image1 = "image/phukien/phukien-dochoithucan.png",
                            product_Image2 = "image/phukien/phukien-dochoithucan.png",
                            product_Image3 = "image/phukien/phukien-dochoithucan.png",
                            product_Image4 = "image/phukien/phukien-dochoithucan.png",
                            product_Image5 = "image/phukien/phukien-dochoithucan.png",
                            product_IsDelete = false,
                            product_Name = "Food Toys",
                            product_Price = 100000.0,
                            product_Rate = 5.0,
                            product_ReProducePrice = 0.0
                        },
                        new
                        {
                            product_Id = "03cf6cc9-12e7-45d1-a101-4cfef8d2525a",
                            product_CategoryId = "977d57c9-4b90-42bd-9c26-1ccf6aaf4005",
                            product_Description = "Coat + Strap",
                            product_Image1 = "image/phukien/phukien-ao_giaythat.png",
                            product_Image2 = "image/phukien/phukien-ao_giaythat.png",
                            product_Image3 = "image/phukien/phukien-ao_giaythat.png",
                            product_Image4 = "image/phukien/phukien-ao_giaythat.png",
                            product_Image5 = "image/phukien/phukien-ao_giaythat.png",
                            product_IsDelete = false,
                            product_Name = "Coat + Strap",
                            product_Price = 100000.0,
                            product_Rate = 5.0,
                            product_ReProducePrice = 0.0
                        },
                        new
                        {
                            product_Id = "575168f7-2b60-4000-b55c-644cd16d233a",
                            product_CategoryId = "977d57c9-4b90-42bd-9c26-1ccf6aaf4005",
                            product_Description = "Throwing dish",
                            product_Image1 = "image/phukien/phukien-dianem.png",
                            product_Image2 = "image/phukien/phukien-dianem.png",
                            product_Image3 = "image/phukien/phukien-dianem.png",
                            product_Image4 = "image/phukien/phukien-dianem.png",
                            product_Image5 = "image/phukien/phukien-dianem.png",
                            product_IsDelete = false,
                            product_Name = "Throwing dish",
                            product_Price = 100000.0,
                            product_Rate = 5.0,
                            product_ReProducePrice = 0.0
                        },
                        new
                        {
                            product_Id = "a54d60f8-45b7-48c1-aa33-39d53ddb2f69",
                            product_CategoryId = "977d57c9-4b90-42bd-9c26-1ccf6aaf4005",
                            product_Description = "Orb of Thorns",
                            product_Image1 = "image/phukien/phukien-quacaugai.png",
                            product_Image2 = "image/phukien/phukien-quacaugai.png",
                            product_Image3 = "image/phukien/phukien-quacaugai.png",
                            product_Image4 = "image/phukien/phukien-quacaugai.png",
                            product_Image5 = "image/phukien/phukien-quacaugai.png",
                            product_IsDelete = false,
                            product_Name = "Orb of Thorns",
                            product_Price = 100000.0,
                            product_Rate = 5.0,
                            product_ReProducePrice = 0.0
                        },
                        new
                        {
                            product_Id = "71184630-c981-412c-b3e4-99970ae5fe15",
                            product_CategoryId = "977d57c9-4b90-42bd-9c26-1ccf6aaf4005",
                            product_Description = "Food Gun",
                            product_Image1 = "image/phukien/phukien-sungbanthucan.png",
                            product_Image2 = "image/phukien/phukien-sungbanthucan.png",
                            product_Image3 = "image/phukien/phukien-sungbanthucan.png",
                            product_Image4 = "image/phukien/phukien-sungbanthucan.png",
                            product_Image5 = "image/phukien/phukien-sungbanthucan.png",
                            product_IsDelete = false,
                            product_Name = "Food Gun",
                            product_Price = 100000.0,
                            product_Rate = 5.0,
                            product_ReProducePrice = 0.0
                        },
                        new
                        {
                            product_Id = "2227bc02-2ef9-4844-9919-c8023a486e26",
                            product_CategoryId = "977d57c9-4b90-42bd-9c26-1ccf6aaf4005",
                            product_Description = "Feather Brush",
                            product_Image1 = "image/phukien/phukien-banchaylong.png",
                            product_Image2 = "image/phukien/phukien-banchaylong.png",
                            product_Image3 = "image/phukien/phukien-banchaylong.png",
                            product_Image4 = "image/phukien/phukien-banchaylong.png",
                            product_Image5 = "image/phukien/phukien-banchaylong.png",
                            product_IsDelete = false,
                            product_Name = "Feather Brush",
                            product_Price = 100000.0,
                            product_Rate = 5.0,
                            product_ReProducePrice = 0.0
                        },
                        new
                        {
                            product_Id = "cc92954b-a5d9-49d7-b79f-78f60443e618",
                            product_CategoryId = "977d57c9-4b90-42bd-9c26-1ccf6aaf4005",
                            product_Description = "Rooster Toys",
                            product_Image1 = "image/phukien/phukien-dochoi_gatrong.png",
                            product_Image2 = "image/phukien/phukien-dochoi_gatrong.png",
                            product_Image3 = "image/phukien/phukien-dochoi_gatrong.png",
                            product_Image4 = "image/phukien/phukien-dochoi_gatrong.png",
                            product_Image5 = "image/phukien/phukien-dochoi_gatrong.png",
                            product_IsDelete = false,
                            product_Name = "Rooster Toys",
                            product_Price = 100000.0,
                            product_Rate = 5.0,
                            product_ReProducePrice = 0.0
                        },
                        new
                        {
                            product_Id = "c3ca3f49-f3d6-46d4-ab26-c6e3c654c9bc",
                            product_CategoryId = "977d57c9-4b90-42bd-9c26-1ccf6aaf4005",
                            product_Description = "Skin Bones",
                            product_Image1 = "image/phukien/phukien-xuongda.png",
                            product_Image2 = "image/phukien/phukien-xuongda.png",
                            product_Image3 = "image/phukien/phukien-xuongda.png",
                            product_Image4 = "image/phukien/phukien-xuongda.png",
                            product_Image5 = "image/phukien/phukien-xuongda.png",
                            product_IsDelete = false,
                            product_Name = "Skin Bones",
                            product_Price = 100000.0,
                            product_Rate = 5.0,
                            product_ReProducePrice = 0.0
                        },
                        new
                        {
                            product_Id = "43d98c4d-59c6-4d5d-a04e-d37d9e6e592f",
                            product_CategoryId = "977d57c9-4b90-42bd-9c26-1ccf6aaf4005",
                            product_Description = "SmartHeart For Adult Dogs",
                            product_Image1 = "image/phukien/phukien-Smartheart_truongthanh.png",
                            product_Image2 = "image/phukien/phukien-Smartheart_truongthanh.png",
                            product_Image3 = "image/phukien/phukien-Smartheart_truongthanh.png",
                            product_Image4 = "image/phukien/phukien-Smartheart_truongthanh.png",
                            product_Image5 = "image/phukien/phukien-Smartheart_truongthanh.png",
                            product_IsDelete = false,
                            product_Name = "SmartHeart For Adult Dogs",
                            product_Price = 1000000.0,
                            product_Rate = 5.0,
                            product_ReProducePrice = 0.0
                        },
                        new
                        {
                            product_Id = "8b6bc4ab-8a38-4220-9608-095f81421976",
                            product_CategoryId = "977d57c9-4b90-42bd-9c26-1ccf6aaf4005",
                            product_Description = "Royal Canin For Small Dogs",
                            product_Image1 = "image/phukien/phukien-roya_chonho.png",
                            product_Image2 = "image/phukien/phukien-roya_chonho.png",
                            product_Image3 = "image/phukien/phukien-roya_chonho.png",
                            product_Image4 = "image/phukien/phukien-roya_chonho.png",
                            product_Image5 = "image/phukien/phukien-roya_chonho.png",
                            product_IsDelete = false,
                            product_Name = "Royal Canin For Small Dogs",
                            product_Price = 100000.0,
                            product_Rate = 5.0,
                            product_ReProducePrice = 0.0
                        },
                        new
                        {
                            product_Id = "8bded664-26ed-403e-9465-8bbbbf010228",
                            product_CategoryId = "977d57c9-4b90-42bd-9c26-1ccf6aaf4005",
                            product_Description = "FAY Dry Bath Powder",
                            product_Image1 = "image/phukien/phukien-phantamkhoFay.png",
                            product_Image2 = "image/phukien/phukien-phantamkhoFay.png",
                            product_Image3 = "image/phukien/phukien-phantamkhoFay.png",
                            product_Image4 = "image/phukien/phukien-phantamkhoFay.png",
                            product_Image5 = "image/phukien/phukien-phantamkhoFay.png",
                            product_IsDelete = false,
                            product_Name = "FAY Dry Bath Powder",
                            product_Price = 100000.0,
                            product_Rate = 5.0,
                            product_ReProducePrice = 0.0
                        },
                        new
                        {
                            product_Id = "6b24aa63-9988-46e6-9fb9-62d4ba873dc5",
                            product_CategoryId = "977d57c9-4b90-42bd-9c26-1ccf6aaf4005",
                            product_Description = "Oliver Shower Gel",
                            product_Image1 = "image/phukien/phukien-suatamoliver.png",
                            product_Image2 = "image/phukien/phukien-suatamoliver.png",
                            product_Image3 = "image/phukien/phukien-suatamoliver.png",
                            product_Image4 = "image/phukien/phukien-suatamoliver.png",
                            product_Image5 = "image/phukien/phukien-suatamoliver.png",
                            product_IsDelete = false,
                            product_Name = "Oliver Shower Gel",
                            product_Price = 100000.0,
                            product_Rate = 5.0,
                            product_ReProducePrice = 0.0
                        });
                });

            modelBuilder.Entity("Database.Entities.UserContact", b =>
                {
                    b.Property<string>("uc_Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("uc_Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("uc_Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("uc_IsDelete")
                        .HasColumnType("bit");

                    b.Property<string>("uc_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("uc_Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("uc_UserCreate")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("uc_Id");

                    b.HasIndex("uc_UserCreate");

                    b.ToTable("UserContact", (string)null);

                    b.HasData(
                        new
                        {
                            uc_Id = "0a30a7dd-e6fc-4e4b-b99e-598e8c00d836",
                            uc_Content = "Content",
                            uc_Email = "Email",
                            uc_IsDelete = false,
                            uc_Name = "Name",
                            uc_Phone = "Phone",
                            uc_UserCreate = "5db2ec3d-8bcf-4bf9-81de-4730297b2f20"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("Roles", (string)null);

                    b.HasDiscriminator<string>("Discriminator").HasValue("IdentityRole");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("RoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("Users", (string)null);

                    b.HasDiscriminator<string>("Discriminator").HasValue("IdentityUser");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("UserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "5db2ec3d-8bcf-4bf9-81de-4730297b2f20",
                            RoleId = "89543239-37ca-49b0-b35f-d78a35a5a06f"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("UserTokens", (string)null);
                });

            modelBuilder.Entity("Database.Entities.Roles", b =>
                {
                    b.HasBaseType("Microsoft.AspNetCore.Identity.IdentityRole");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("isDelete")
                        .HasColumnType("bit");

                    b.ToTable("Roles");

                    b.HasDiscriminator().HasValue("Roles");

                    b.HasData(
                        new
                        {
                            Id = "89543239-37ca-49b0-b35f-d78a35a5a06f",
                            ConcurrencyStamp = "88daf35f-b3f2-4280-b4fd-51af026a242c",
                            Name = "ADMIN",
                            NormalizedName = "Admin",
                            Description = "admin",
                            isDelete = false
                        });
                });

            modelBuilder.Entity("Database.Entities.Users", b =>
                {
                    b.HasBaseType("Microsoft.AspNetCore.Identity.IdentityUser");

                    b.Property<DateTime>("DoB")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("isDelete")
                        .HasColumnType("bit");

                    b.ToTable("Users");

                    b.HasDiscriminator().HasValue("Users");

                    b.HasData(
                        new
                        {
                            Id = "5db2ec3d-8bcf-4bf9-81de-4730297b2f20",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "c75b26b2-2526-4ea2-b068-43b77c58d8fc",
                            Email = "admin@gmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMIN@GMAIL.COM",
                            NormalizedUserName = "ADMIN@GMAIL.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAECDNtWNOXpMoh2XQUcdBeC6cNOC41Is/uVJleEtg8+GcF5rDEUT2upAQLWPG6+klrw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "e9cb5b3d-8fe6-4de0-8805-c681f63870b1",
                            TwoFactorEnabled = false,
                            UserName = "Admin",
                            DoB = new DateTime(2022, 10, 22, 23, 17, 22, 26, DateTimeKind.Local).AddTicks(8907),
                            FirstName = "FirstName",
                            LastName = "LastName",
                            isDelete = false
                        });
                });

            modelBuilder.Entity("Database.Entities.Bills", b =>
                {
                    b.HasOne("Database.Entities.Users", "Users")
                        .WithMany("bills")
                        .HasForeignKey("bill_UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Users");
                });

            modelBuilder.Entity("Database.Entities.IntroducePage", b =>
                {
                    b.HasOne("Database.Entities.Users", "users")
                        .WithMany("introducePage")
                        .HasForeignKey("introduce_UserCreate")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("users");
                });

            modelBuilder.Entity("Database.Entities.Pets", b =>
                {
                    b.HasOne("Database.Entities.PetCategories", "petCategories")
                        .WithMany("pets")
                        .HasForeignKey("pet_CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("petCategories");
                });

            modelBuilder.Entity("Database.Entities.PettInBill", b =>
                {
                    b.HasOne("Database.Entities.Bills", "bills")
                        .WithMany("pettInBill")
                        .HasForeignKey("pib_BillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Database.Entities.Pets", "pets")
                        .WithMany("pettInBill")
                        .HasForeignKey("pib_PetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("bills");

                    b.Navigation("pets");
                });

            modelBuilder.Entity("Database.Entities.ProductInBill", b =>
                {
                    b.HasOne("Database.Entities.Bills", "bills")
                        .WithMany("productInBill")
                        .HasForeignKey("proib_BillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Database.Entities.Products", "products")
                        .WithMany("productInBill")
                        .HasForeignKey("proib_ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("bills");

                    b.Navigation("products");
                });

            modelBuilder.Entity("Database.Entities.Products", b =>
                {
                    b.HasOne("Database.Entities.ProductCategories", "productCategories")
                        .WithMany("products")
                        .HasForeignKey("product_CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("productCategories");
                });

            modelBuilder.Entity("Database.Entities.UserContact", b =>
                {
                    b.HasOne("Database.Entities.Users", "users")
                        .WithMany("userContact")
                        .HasForeignKey("uc_UserCreate")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("users");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Database.Entities.Bills", b =>
                {
                    b.Navigation("pettInBill");

                    b.Navigation("productInBill");
                });

            modelBuilder.Entity("Database.Entities.PetCategories", b =>
                {
                    b.Navigation("pets");
                });

            modelBuilder.Entity("Database.Entities.Pets", b =>
                {
                    b.Navigation("pettInBill");
                });

            modelBuilder.Entity("Database.Entities.ProductCategories", b =>
                {
                    b.Navigation("products");
                });

            modelBuilder.Entity("Database.Entities.Products", b =>
                {
                    b.Navigation("productInBill");
                });

            modelBuilder.Entity("Database.Entities.Users", b =>
                {
                    b.Navigation("bills");

                    b.Navigation("introducePage");

                    b.Navigation("userContact");
                });
#pragma warning restore 612, 618
        }
    }
}
